### ISSUE TITLE
Error while starting homie-server

### ISSUE THREAD

**Issue by SasaTepic** [marvinroger/homie-server#7] opened 2016-04-19 13:18 UTC
When I try to run homie-server, it complains about _"/.homie"_ directory
I have created _.homie_ directory in my home directory.
System is Ubuntu 14.04 on Odroid-C1
`sasa@server:~> homie

/usr/lib/node_modules/homie-server/index.js:70
var DEFAULT_DATADIR = _path2.default.join(_os2.default.homedir(), '/.homie');
                                                       ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (/usr/lib/node_modules/homie-server/index.js:70:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/homie-server/bin/cli.js:18:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
`

**Comment by marvinroger** [comment] 2016-04-19 13:26
This is not a bug with the directory, but with the compilation from ES2015 to CommonJS. Anyway, I'll soon publish a new version so it'll probably be fixed by itself with the Babel updates.

**Comment by marvinroger** [comment] 2016-04-19 13:30
Forget what I just said.

Are you using Node < 4.0.0? The `homedir` method was added in this version of node, so I'll need to bump the minimum required version to 4.0.0.

**Comment by SasaTepic** [comment] 2016-04-19 14:06
I was using node v0.15.12,
I've installed v5.10.1 and there's no error any more.

Is there english version of site?

**Comment by marvinroger** [comment] 2016-04-19 14:10
This is very much a project in alpha, but this is planned (#2). I can't say when!

**Closed as completed by marvinroger** 2016-04-19 14:10 UTC
Labels: bug
